//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Service.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Schedule = new HashSet<Schedule>();
            this.ScheduleAll = new HashSet<ScheduleAll>();
            this.Person1 = new HashSet<Person>();
        }
    
        public int ClassID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> ClassRoomID { get; set; }
        public Nullable<int> TeacherID { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
        public virtual Course Course { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual ICollection<ScheduleAll> ScheduleAll { get; set; }
        public virtual ICollection<Person> Person1 { get; set; }
    }
}
