//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Service.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Class = new HashSet<Class>();
            this.User = new HashSet<User>();
            this.Class1 = new HashSet<Class>();
        }
    
        public int PersonID { get; set; }
        public string Name { get; set; }
        public string LastName1 { get; set; }
        public string LastName2 { get; set; }
        public string CellPhone { get; set; }
    
        public virtual ICollection<Class> Class { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<Class> Class1 { get; set; }
    }
}
