//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Service.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Class = new HashSet<Class>();
            this.User = new HashSet<User>();
            this.Class1 = new HashSet<Class>();
        }
    
        public int PersonID { get; set; }
        public string Name { get; set; }
        public string LastName1 { get; set; }
        public string LastName2 { get; set; }
        public string CellPhone { get; set; }
    
        public virtual ICollection<Class> Class { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<Class> Class1 { get; set; }
    }
}
