//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Service.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleAll
    {
        public int ScheduleAllID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int State { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
