//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Service.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public Seat()
        {
            this.ClassRoom = new HashSet<ClassRoom>();
        }
    
        public int SeatID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ClassRoom> ClassRoom { get; set; }
    }
}
