//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Service.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public Seat()
        {
            this.ClassRoom = new HashSet<ClassRoom>();
        }
    
        public int SeatID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ClassRoom> ClassRoom { get; set; }
    }
}
